### ISSUE TITLE
Logika | Możliwe ruchy dla figury: Wieża

### ISSUE THREAD

**Issue by MateuszNaKodach** [nowakprojects/CodersCamp2020.Project.TypeScript.Chess#17]
Zaimplementuj klasę oznaczającą wieżę. 
Klasa powinna mieć metodę, która na podstawie przekazanych parametrów (załóż jakiego typu muszą to być parametry i co zawierać) zwróci ruchy, jakie może wykonać wieża.

Nie musisz robić implementacji argumentów. Np. utwórz interfejs, który zwróci Ci wymagane informacje o sytuacji na szachownicy. W przypadku testów zamockuj działanie interfejsu.

Implementację wykonaj w katalogu **model**. Zapomnij o view.

Wynik tego zadania pomoże nam w ustaleniu uniwersalnego sposobu na implementację reszty bierek.

**Comment by MateuszNaKodach** [comment]
Ania pyta:
```
Nie musisz robić implementacji argumentów. ?
nie rozumiem, o co z tym chodzi
```

Chodzi o to, że np. jeśli zrobisz, że jako argument dostajesz np. szachownicę. To nie musisz pisać działania całej szachownicy. Wystarczy, że ta szachownica będzie zadeklarowanym interfejsem z oczekiwanymi przez Ciebie metodami.

Ktos wykonujacy w innym tasku implementacje szachownicy, spróbuje spełnić te założenia.

**Comment by annalamperska** [comment]
Czy interfejsy wydzielamy w jakichś osobnych plikach, czy powinny znaleźć się razem z klasą?

**Comment by MateuszNaKodach** [comment]
Pewnie jak zawsze "to zależy". Ale raczej w osobnych :)

**Comment by annalamperska** [comment]
approved
