### ISSUE TITLE
MODEL | Ruchy dla skoczka

### ISSUE THREAD

**Issue by PiotrRynio** [nowakprojects/CodersCamp2020.Project.TypeScript.Chess#22]
W razie wątpliwości rozważ i podpytaj. Weź jako pewnik, że czegoś może brakować! (Pamiętaj, ze PM nie musiał przewidzieć wszystkiego).
Patrz na "wieżę".
Implementację wykonaj w katalogu model. Zapomnij o view.

**Comment by nowakprojects** [comment]
Approved
