### ISSUE TITLE
MODEL | Ruchy dla "hetmana"

### ISSUE THREAD

**Issue by PiotrRynio** [nowakprojects/CodersCamp2020.Project.TypeScript.Chess#25]
W razie wątpliwości rozważ i podpytaj. Weź jako pewnik, że czegoś może brakować! (Pamiętaj, ze PM nie musiał przewidzieć wszystkiego).
Patrz na "ruchy wieży".
Implementację wykonaj w katalogu model. Zapomnij o view.

**Comment by nowakprojects** [comment]
Approved
