### ISSUE TITLE
MODEL | Obiekt Figury

### ISSUE THREAD

**Issue by PiotrRynio** [nowakprojects/CodersCamp2020.Project.TypeScript.Chess#29]
W razie wątpliwości rozważ i podpytaj. Weź jako pewnik, że czegoś może brakować! (Pamiętaj, ze PM nie musiał przewidzieć wszystkiego).

Stworzenie obiektu (figury), który posiada informacje o:
- kolorze
- statusie społecznym
- o czym czy jeszcze żyje (czy już nie) "isLived"?
- o tym czy został promowany "isPromoted"?
- na co został promowany (wieża, królowa, czy coś innego)?

**Comment by MateuszNaKodach** [comment]
Chciałbym zasugerowac, że to jest nam niepotrzebne.
Zrealizujmy najpierw wykonywanie ruchu przez bierkę. Czyli silnik gry
1. Sprawdza dozwolone ruchy
2. Bierka jest przesuwana jesli wybrany ruch to ten dozwolony.

Jeśli będziemy zwracać zdarzenia z metody ruchu - to wszystko otrzymamy :)
